mutation addUserProduct($userStore: ID!, $input: ProductCart!) {
  addUserProduct(userStore: $userStore, input: $input) {
    products {
      id
      amount
      price
      title
      total
    }
  }
}